version: "3"
services:
  tempo:
    image: grafana/tempo:latest
    command: "-target=distributor -config.file=/etc/tempo.yml"
    volumes:
      - ./tempo.yml:/etc/tempo.yml
    ports:
      - "3200:3200/tcp"
      - "4317:4317/tcp"