# Generated by Django 4.0.5 on 2022-06-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='updated_by',
        ),
    ]
