# Generated by Django 4.0.5 on 2022-06-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=6),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], max_length=6),
        ),
    ]
