name: Publish
on:
  push:
    tags:
      - v*
jobs:
  publish-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          logout: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      
      - name: Extract Git Tag
        run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      
      - name: Build and push Docker 
        uses: docker/build-push-action@v2
        with:
          push: true
          tags:  
            - ghcr.io/chazapp/incidents-api:latest
            - ghcr.io/chazapp/incidents-api:$GIT_TAG
    
  publish-arm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2      
      
      - name: Checkout assets
        uses: actions/checkout@v2

      - name: Extract Git Tag
        run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          logout: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags:  
            - ghcr.io/chazapp/mtvs-back:arm64-latest
            - ghcr.io/chazapp/incidents-api:$GIT_TAG
          platforms: linux/arm64