name: Publish
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  publish-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
            logout: true
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: ghcr.io

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            incidents-api
            ghcr.io/username/app
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}-x86
            type=semver,pattern={{major}}.{{minor}}-x86
            type=semver,pattern={{major}}-x86
            type=sha
      
      - name: Build and push Docker 
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
  publish-arm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2      
      
      - name: Checkout assets
        uses: actions/checkout@v2

      - name: Extract Git Tag
        run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          logout: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            incidents-api
            ghcr.io/username/app
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}-arm
            type=semver,pattern={{major}}.{{minor}}-arm
            type=semver,pattern={{major}}-arm
            type=sha
      
      - name: Build and push Docker 
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
