name: Python tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          coverage run --source='./incidents' manage.py test incidents
      - name: Generate coverage report
        run: |
          coverage report -m --fail-under=80
      - name: Send coverage report
        uses: codecov/codecov@v2
        with:
          verbose: true
          fail_ci_if_error: true
          